x = "Hello World" # str
x = 20 # int
x = 20.5 # float
x = ["apple", "banana", "cherry"] # list
x = ("apple", "banana", "cherry") # tuple
x = {"name": "patcharanut", "age": 26} # dict
x = {"apple", "banana", "cherry"} # set
x = frozenset({"apple", "banana", "cherry"}) #frozenset
x = True # boolean
x = b"hello" # byte